# Generated by Django 6.1.1 on 2026-10-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
