# Generated by Django 6.1.1 on 2026-10-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_images_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
